# Site settings
title: 'Coming Together'
subtitle: 'in Skokie & Niles Township'
email: your-email@domain.com
series_title: 'Voices of Race'
series_dates: 'January 11 to Feburary 28, 2015'
description: 'A cultural and literary series exploring race and how it affects us and our community.'
baseurl: "/comingtogether" # the subpath of your site, e.g. /blog/
url: "http://comingtogether.in" # the base hostname & protocol for your site
permalink: /events/:year/:month/:day/:title
exclude: [README.md, bower.json, bower_components, scss, node_modules, gulpfile.js]
defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'

# Build settings
markdown: kramdown
